### 예약 전체 조회
GET http://localhost:8080/reservations

### 특정 유저의 예약 조회 (유저 ID를 1로 가정)
GET http://localhost:8080/reservations/user/1

### 특정 아이템 타입과 날짜에 대한 예약 조회
# itemType을 'room'으로 설정하고 날짜를 2024-01-01로 설정
GET http://localhost:8080/reservations/room?date=2024-01-01

### 특정 아이템에 대한 예약 생성 (itemId를 123으로 가정)
POST http://localhost:8080/reservations/1
Content-Type: application/json

{
  "userId": "3",
  "startDate": "2024-01-01T10:00:00Z",
  "endDate": "2024-01-01T12:00:00Z",
  "status": "reserved",
  "details": "테스트입니당~"
}

### 특정 예약 수정 (reservationId를 456으로 가정)
PATCH http://localhost:8080/reservations/456
Content-Type: application/json

{
  "startDate": "2024-01-02T10:00:00Z",
  "endDate": "2024-01-02T12:00:00Z"
}

### 특정 예약 삭제 (reservationId를 456으로 가정)
DELETE http://localhost:8080/reservations/456